title: Chengyi Yang's Homepage
page-top-title: Chengyi Yang
top-section-bg-text: 重要的是百折不屈的心
home-subtitle: Chengyi Yang&ensp;|&ensp;杨澄逸
copyright-text: '&copy; Chengyi Yang 2023-2025. All Rights Reserved.'
