title: Yixin Huang's Homepage
page-top-title: Yixin Huang
top-section-bg-text: Be what you wanna be
home-subtitle: Yixin Huang&ensp;|&ensp;黄宜欣
copyright-text: '&copy; Yixin Huang 2023-2025. All Rights Reserved.'
